---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mrprober-config
  namespace: monitoring
data:
  "mrprober.yaml": |
    global:
      tickrate: 15
      web:
        listenAddress: "0.0.0.0:9100"
        metricsPath: "/metrics"
                  
    rules:
      - name: "Test google.com on TCP port 443 with timeout set at 1 ms (must fail)"
        probe: "net"
        args:
          - "tcp://google.com:443"
          - "1ms"
          
      - name: "Test kubernetes.default.svc on TCP port 443 with timeout set at 20 ms"
        probe: "net"
        args:
          - "tcp://kubernetes.default.svc:443"
          - "20ms"

      - name: "Test application endpoint"
        probe: "net"
        args:
          - "udp://test.internal:24224"
          - "100ms"

    alerts: []
