{
 "title": "Kubernetes / Addons / Mr Prober",
 "description": "DaemonSet Utility for reporting various host probes.",
 "tags": [
  "monitoring",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "mrprober" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(mrprober_meta{job=~\"$job\"}, node)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mrprober_meta{job=~\"$job\", node=\"$node\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net/TCP - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mrprober_net_tcp{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net/UDP - Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mrprober_net_udp{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Net Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "NET/TCP - Rules",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "mrprober_net_tcp{job=~\"$job\", src=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NET/UDP - Rules",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "mrprober_net_udp{job=~\"$job\", src=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mrprober-exporter by instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Reserved Memory",
     "type": "timeseries",
     "description": "Average total bytes of memory reserved across all process instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by(job)(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}} (avg)"
      }
     ]
    },
    {
     "title": "Stack Memory Use",
     "type": "timeseries",
     "description": "Average stack memory usage across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job) (go_memstats_stack_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: stack inuse (avg)"
      }
     ]
    },
    {
     "title": "Other Memory Reservations",
     "type": "timeseries",
     "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_mspan_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: mspan (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_mcache_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: mcache (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_buck_hash_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: buck hash (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_gc_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: gc (avg)"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_heap_sys_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: heap reserved (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: heap in use (avg)"
      }
     ]
    },
    {
     "title": "Allocation Rate, Bytes",
     "type": "timeseries",
     "description": "Average allocation rate in bytes per second, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by (job)(rate(go_memstats_alloc_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{job}}: bytes malloced/s (avg)"
      }
     ]
    },
    {
     "title": "Heap Object Allocation Rate",
     "type": "timeseries",
     "description": "Average rate of heap object allocation, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{job}}: obj mallocs/s (avg)"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "description": "Average number of live memory objects across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(job)(go_memstats_mallocs_total{job=~\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: object count (avg)"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Average number of goroutines across instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job)(go_goroutines{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: goroutine count (avg)"
      }
     ]
    },
    {
     "title": "GC min & max duration",
     "type": "timeseries",
     "description": "The min and max Garbage Collector duration in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"0\", job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: min gc time (avg)"
      },
      {
       "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"1\", job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: max gc time (avg)"
      }
     ]
    },
    {
     "title": "Next GC, Bytes",
     "type": "timeseries",
     "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_next_gc_bytes{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: next gc bytes (avg)"
      }
     ]
    }
   ]
  }
 ]
}